function filter = helperInitPointFilter(detection)
    % [x;vx;y;vy;w;z;vz].
    filter3D = initctekf(detection);
    % Use the first 5 states to initialize the 2-D filter
    filter = trackingEKF('State',filter3D.State(1:5),...
    'StateCovariance',filter3D.StateCovariance(1:5,1:5),...
    'HasAdditiveProcessNoise',false,...
    'ProcessNoise',diag([1 1 3]),...
    'StateTransitionFcn',@constturn,...
    'MeasurementFcn',@ctmeas,...
    'MeasurementJacobianFcn',@ctmeasjac,...
    'StateTransitionJacobianFcn',@constturnjac);
end