function [scenario, egoVehicle] = P11data2()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 13-Jan-2022 11:48:48

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 10);

% Add all road segments
roadCenters = [-6.9 16.2 0;
    26.9 18.2 0;
    37.7 19.1 0;
    51.2 17.2 0;
    60.6 8.1 0;
    66.6 -21.8 0];
laneSpecification = lanespec(4, 'Width', 6);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-8.52 16.22 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-7.7 20.3 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-7.7 20.3 0;
    29.3 21.8 0;
    55.3 18.4 0;
    63 12.6 0;
    67.1 4 0;
    69.7 -8.5 0;
    70.2 -22 0];
speed = [10;10;10;10;10;10;10];
smoothTrajectory(car1, waypoints, speed);

