function [scenario, egoVehicle] = P11data()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 13-Jan-2022 11:29:55

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 10);

% Add all road segments
roadCenters = [-6.9 16.2 0;
    26.9 18.2 0;
    37.7 19.1 0;
    51.2 17.2 0;
    60.6 8.1 0;
    66.6 -21.8 0];
laneSpecification = lanespec(4, 'Width', 6);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-8.52 16.22 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

